apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: phpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: arifislam/php-app:21_5
        ports:
        - containerPort: 80
